language: ruby

before_install: "gem install bones"
install:        "rake gem:install_dependencies"

script: "rake"

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.7
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby-9.2.9.0
